# Generated by Django 5.0.4 on 2025-05-09 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ro', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ro', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=16)),
                ('api_ref', models.CharField(max_length=64, unique=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='OddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=32)),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=16)),
                ('prob_home', models.FloatField()),
                ('prob_draw', models.FloatField()),
                ('prob_away', models.FloatField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='core_predic_created_7687c2_idx')],
                'unique_together': {('match', 'model_version')},
            },
        ),
    ]
