# Generated by Django 5.0.4 on 2025-05-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oddssnapshot',
            unique_together={('match', 'bookmaker')},
        ),
        migrations.AddField(
            model_name='oddssnapshot',
            name='odds_away',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oddssnapshot',
            name='odds_draw',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='oddssnapshot',
            name='odds_home',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='oddssnapshot',
            name='bookmaker',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='oddssnapshot',
            index=models.Index(fields=['match', 'bookmaker'], name='core_oddssn_match_i_ace579_idx'),
        ),
        migrations.AddIndex(
            model_name='oddssnapshot',
            index=models.Index(fields=['fetched_at'], name='core_oddssn_fetched_5e61c5_idx'),
        ),
        migrations.RemoveField(
            model_name='oddssnapshot',
            name='away_odds',
        ),
        migrations.RemoveField(
            model_name='oddssnapshot',
            name='draw_odds',
        ),
        migrations.RemoveField(
            model_name='oddssnapshot',
            name='home_odds',
        ),
    ]
