# Generated by Django 5.0.4 on 2025-05-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_league_id_alter_match_api_ref_alter_match_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddssnapshot',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_snapshots', to='core.match'),
        ),
    ]
