# Generated by Django 5.1.7 on 2025-05-12 15:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_oddssnapshot_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddssnapshot',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MatchScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.CharField(db_index=True, max_length=64)),
                ('home_team_score', models.FloatField()),
                ('away_team_score', models.FloatField()),
                ('confidence_level', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=32)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recommended_bet', models.CharField(max_length=128)),
                ('predicted_outcome', models.CharField(max_length=16)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='core.match')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['fixture_id'], name='core_matchs_fixture_1a56ec_idx'), models.Index(fields=['generated_at'], name='core_matchs_generat_1aa9a2_idx'), models.Index(fields=['predicted_outcome'], name='core_matchs_predict_10a869_idx')],
            },
        ),
    ]
