# Generated by Django 5.1.7 on 2025-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_league_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscoremodel',
            name='expected_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
