# Generated by Django 5.1.7 on 2025-05-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_statistics_fields'),
        ('core', '0011_match_venue'),
    ]

    operations = [
    ]
