# Generated by Django 5.1.7 on 2025-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_0002_add_statistics_fields_0011_match_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-kickoff'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('1H', 'First Half'), ('HT', 'Half Time'), ('2H', 'Second Half'), ('FT', 'Full Time'), ('AET', 'After Extra Time'), ('PEN', 'Penalties'), ('PST', 'Postponed'), ('CANC', 'Cancelled'), ('ABD', 'Abandoned'), ('TBA', 'To Be Announced'), ('WO', 'Walkover'), ('LIVE', 'Live'), ('ET', 'Extra Time'), ('BT', 'Break Time'), ('APEN', 'After Penalties'), ('SUSP', 'Suspended'), ('INT', 'Interrupted'), ('POSTP', 'Postponed'), ('AWARDED', 'Awarded')], default='NS', max_length=10),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['kickoff'], name='core_match_kickoff_88f818_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='core_match_status_b71399_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['api_ref'], name='core_match_api_ref_5ce729_idx'),
        ),
    ]
