# Generated by Django 5.0.4 on 2025-10-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_match_options_alter_match_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('accuracy_percent', models.FloatField(default=0.0)),
                ('home_predictions', models.IntegerField(default=0)),
                ('home_correct', models.IntegerField(default=0)),
                ('home_accuracy', models.FloatField(default=0.0)),
                ('draw_predictions', models.IntegerField(default=0)),
                ('draw_correct', models.IntegerField(default=0)),
                ('draw_accuracy', models.FloatField(default=0.0)),
                ('away_predictions', models.IntegerField(default=0)),
                ('away_correct', models.IntegerField(default=0)),
                ('away_accuracy', models.FloatField(default=0.0)),
                ('total_profit_loss', models.FloatField(default=0.0)),
                ('roi_percent', models.FloatField(default=0.0)),
                ('high_confidence_predictions', models.IntegerField(default=0)),
                ('high_confidence_correct', models.IntegerField(default=0)),
                ('high_confidence_accuracy', models.FloatField(default=0.0)),
                ('medium_confidence_predictions', models.IntegerField(default=0)),
                ('medium_confidence_correct', models.IntegerField(default=0)),
                ('medium_confidence_accuracy', models.FloatField(default=0.0)),
                ('low_confidence_predictions', models.IntegerField(default=0)),
                ('low_confidence_correct', models.IntegerField(default=0)),
                ('low_confidence_accuracy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Performance Snapshot',
                'verbose_name_plural': 'Performance Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='oddssnapshot',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchmetadata',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchscoremodel',
            name='match',
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.IntegerField(db_index=True, unique=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField(db_index=True)),
                ('predicted_outcome', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('probability_home', models.FloatField()),
                ('probability_draw', models.FloatField()),
                ('probability_away', models.FloatField()),
                ('odds_home', models.FloatField(blank=True, null=True)),
                ('odds_draw', models.FloatField(blank=True, null=True)),
                ('odds_away', models.FloatField(blank=True, null=True)),
                ('bookmaker', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('model_count', models.IntegerField(default=0)),
                ('consensus', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('ensemble_strategy', models.CharField(default='consensus_ensemble', max_length=50)),
                ('actual_outcome', models.CharField(blank=True, max_length=10, null=True)),
                ('actual_score_home', models.IntegerField(blank=True, null=True)),
                ('actual_score_away', models.IntegerField(blank=True, null=True)),
                ('match_status', models.CharField(blank=True, max_length=20, null=True)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('profit_loss_10', models.FloatField(blank=True, null=True)),
                ('roi_percent', models.FloatField(blank=True, null=True)),
                ('prediction_logged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('result_logged_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-kickoff'],
                'indexes': [models.Index(fields=['fixture_id'], name='core_predic_fixture_182063_idx'), models.Index(fields=['kickoff'], name='core_predic_kickoff_befc97_idx'), models.Index(fields=['predicted_outcome'], name='core_predic_predict_b9b2e1_idx'), models.Index(fields=['was_correct'], name='core_predic_was_cor_49038f_idx'), models.Index(fields=['league'], name='core_predic_league_ce35ac_idx')],
            },
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='OddsSnapshot',
        ),
        migrations.DeleteModel(
            name='MatchMetadata',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='MatchScoreModel',
        ),
    ]
