# Generated by Django 5.0.4 on 2025-10-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_performancesnapshot_remove_match_league_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.IntegerField(help_text='SportMonks fixture ID', unique=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('home_mentions_count', models.IntegerField(default=0)),
                ('away_mentions_count', models.IntegerField(default=0)),
                ('home_sentiment_score', models.FloatField(default=0.0, help_text='Sentiment score -1 to +1')),
                ('away_sentiment_score', models.FloatField(default=0.0, help_text='Sentiment score -1 to +1')),
                ('public_attention_ratio', models.FloatField(default=0.0, help_text='Public attention level 0 to 1')),
                ('trap_score', models.IntegerField(default=0, help_text='Trap score 0 to 10')),
                ('trap_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('extreme', 'Extreme Risk')], default='low', max_length=10)),
                ('alert_message', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('confidence_divergence', models.FloatField(default=0.0)),
                ('data_sources', models.JSONField(default=list, help_text='List of data sources used')),
                ('top_keywords', models.JSONField(default=list, help_text='Top keywords from sentiment analysis')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_mentions', models.IntegerField(default=0)),
                ('analysis_version', models.CharField(default='v1.0', max_length=10)),
            ],
            options={
                'verbose_name': 'Match Sentiment',
                'verbose_name_plural': 'Match Sentiments',
                'ordering': ['-match_date', '-scraped_at'],
                'indexes': [models.Index(fields=['fixture_id'], name='core_matchs_fixture_3743b7_idx'), models.Index(fields=['match_date'], name='core_matchs_match_d_b41101_idx'), models.Index(fields=['trap_score'], name='core_matchs_trap_sc_d2da31_idx'), models.Index(fields=['trap_level'], name='core_matchs_trap_le_e1971d_idx'), models.Index(fields=['league'], name='core_matchs_league_c8e00f_idx'), models.Index(fields=['scraped_at'], name='core_matchs_scraped_f541c3_idx')],
            },
        ),
    ]
