# Generated by Django 5.0.4 on 2025-10-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_matchsentiment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchSentiment',
        ),
    ]
