# Generated by Django 5.0.4 on 2025-10-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_matchsentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['is_recommended'], name='core_predic_is_reco_d92c08_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['is_recommended', 'was_correct'], name='core_predic_is_reco_fb7347_idx'),
        ),
    ]
