# Generated by Django 5.0.4 on 2025-11-04 12:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_is_recommended_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('initial_bankroll', models.DecimalField(decimal_places=2, help_text='Starting bankroll amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_bankroll', models.DecimalField(decimal_places=2, help_text='Current available bankroll', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('daily_loss_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum loss allowed per day', max_digits=10, null=True)),
                ('weekly_loss_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum loss allowed per week', max_digits=10, null=True)),
                ('max_stake_percentage', models.FloatField(default=5.0, help_text='Maximum percentage of bankroll to stake on single bet', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(25.0)])),
                ('staking_strategy', models.CharField(choices=[('kelly', 'Kelly Criterion'), ('kelly_fractional', 'Fractional Kelly (1/4)'), ('fixed_percentage', 'Fixed Percentage'), ('fixed_amount', 'Fixed Amount'), ('confidence_scaled', 'Confidence Scaled')], default='kelly_fractional', max_length=20)),
                ('fixed_stake_amount', models.DecimalField(blank=True, decimal_places=2, help_text='For fixed_amount strategy', max_digits=10, null=True)),
                ('fixed_stake_percentage', models.FloatField(blank=True, help_text='For fixed_percentage strategy', null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('risk_profile', models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='balanced', max_length=20)),
                ('is_daily_limit_reached', models.BooleanField(default=False)),
                ('is_weekly_limit_reached', models.BooleanField(default=False)),
                ('daily_loss_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('weekly_loss_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_daily_reset', models.DateField(default=django.utils.timezone.now)),
                ('last_weekly_reset', models.DateField(default=django.utils.timezone.now)),
                ('total_bets_placed', models.IntegerField(default=0)),
                ('total_wagered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('roi_percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Bankroll',
                'verbose_name_plural': 'User Bankrolls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StakeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_stake_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_stake_percentage', models.FloatField()),
                ('strategy_used', models.CharField(max_length=20)),
                ('kelly_percentage', models.FloatField(blank=True, null=True)),
                ('kelly_full_stake', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kelly_fraction_used', models.FloatField(default=0.25)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('risk_explanation', models.TextField()),
                ('has_warnings', models.BooleanField(default=False)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('bankroll_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_stake_allowed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stake_recommendations', to='core.predictionlog')),
                ('bankroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stake_recommendations', to='core.userbankroll')),
            ],
            options={
                'verbose_name': 'Stake Recommendation',
                'verbose_name_plural': 'Stake Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankrollTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('bet_placed', 'Bet Placed'), ('bet_won', 'Bet Won'), ('bet_lost', 'Bet Lost'), ('bet_void', 'Bet Void'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('fixture_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('match_description', models.CharField(blank=True, max_length=200)),
                ('selected_outcome', models.CharField(blank=True, max_length=10)),
                ('odds', models.FloatField(blank=True, null=True)),
                ('stake_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('potential_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actual_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bankroll_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bankroll_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommended_stake', models.DecimalField(blank=True, decimal_places=2, help_text='What SmartBet recommended', max_digits=10, null=True)),
                ('staking_strategy_used', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled_won', 'Settled - Won'), ('settled_lost', 'Settled - Lost'), ('settled_void', 'Settled - Void')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('prediction_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankroll_transactions', to='core.predictionlog')),
                ('bankroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.userbankroll')),
            ],
            options={
                'verbose_name': 'Bankroll Transaction',
                'verbose_name_plural': 'Bankroll Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bankroll', 'transaction_type'], name='core_bankro_bankrol_615e61_idx'), models.Index(fields=['bankroll', 'status'], name='core_bankro_bankrol_b2e0da_idx'), models.Index(fields=['fixture_id'], name='core_bankro_fixture_b07ef7_idx')],
            },
        ),
    ]
