# Generated by Django 5.0.4 on 2025-11-07 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userbankroll_stakerecommendation_bankrolltransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankroll',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankroll', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbankroll',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='userbankroll',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('session_id__isnull', False), _connector='OR'), name='user_or_session_required'),
        ),
    ]
