# Generated by Django 5.2.7 on 2025-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userbankroll_user_alter_userbankroll_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='away_team_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='home_team_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
