# Generated by Django 5.2.7 on 2026-01-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_predictionlog_away_team_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='market_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='market_type',
            field=models.CharField(choices=[('1x2', 'Match Result'), ('btts', 'Both Teams to Score'), ('over_under_2.5', 'Over/Under 2.5'), ('double_chance', 'Double Chance')], db_index=True, default='1x2', max_length=20),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='market_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['is_recommended', '-kickoff'], name='core_predic_is_reco_b19a24_idx'),
        ),
    ]
