# Generated by Django 5.1.3 on 2026-07-29 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='odds_provenance',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='prediction_run_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='pricing_integrity_status',
            field=models.CharField(choices=[('verified', 'Verified — price captured by the deterministic selector'), ('legacy_unverified', 'Legacy — original odds cannot be verified'), ('audit_excluded', 'Quarantined — known bad data'), ('missing_provenance', 'Missing or invalid price provenance')], db_index=True, default='legacy_unverified', help_text='Only PRICING_VERIFIED rows may appear in public pricing statistics.', max_length=24),
        ),
        migrations.CreateModel(
            name='PublishedClaim',
            fields=[
                ('claim_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('fixture_id', models.IntegerField(db_index=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField()),
                ('market_type', models.CharField(max_length=20)),
                ('predicted_outcome', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('odds', models.FloatField()),
                ('odds_provenance', models.JSONField()),
                ('odds_captured_at', models.DateTimeField(blank=True, null=True)),
                ('prediction_generated_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_version', models.CharField(blank=True, max_length=64, null=True)),
                ('prediction_run_id', models.CharField(blank=True, max_length=64, null=True)),
                ('pricing_integrity_status', models.CharField(choices=[('verified', 'Verified — price captured by the deterministic selector'), ('legacy_unverified', 'Legacy — original odds cannot be verified'), ('audit_excluded', 'Quarantined — known bad data'), ('missing_provenance', 'Missing or invalid price provenance')], default='verified', max_length=24)),
                ('claim_hash', models.CharField(max_length=64, unique=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_claims', to='core.predictionlog')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['fixture_id'], name='core_publis_fixture_8be9b2_idx'), models.Index(fields=['-published_at'], name='core_publis_publish_6ede00_idx')],
            },
        ),
    ]
