# Generated by Django 5.1.3 on 2026-07-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_predictionlog_odds_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedclaim',
            name='correction_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publishedclaim',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='core.publishedclaim'),
        ),
    ]
