# Generated by Django 5.1.3 on 2026-07-30 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_publishedclaim_correction_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedClaimResult',
            fields=[
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='result', serialize=False, to='core.publishedclaim')),
                ('status', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void'), ('CANCELLED', 'Cancelled')], max_length=12)),
                ('actual_score_home', models.IntegerField(blank=True, null=True)),
                ('actual_score_away', models.IntegerField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_source', models.CharField(default='sportmonks', max_length=64)),
                ('result_reference', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Published Claim Result',
            },
        ),
        migrations.AddField(
            model_name='publishedclaim',
            name='claim_hash_version',
            field=models.CharField(default='v1', max_length=8),
        ),
    ]
