# Generated by Django 5.1.3 on 2026-07-30 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_publishedclaimresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('prediction_run_id', models.CharField(db_index=True, max_length=64)),
                ('fixture_id', models.IntegerField(db_index=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField()),
                ('market_type', models.CharField(max_length=20)),
                ('predicted_outcome', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('model_version', models.CharField(blank=True, max_length=64, null=True)),
                ('odds', models.FloatField(blank=True, null=True)),
                ('odds_provenance', models.JSONField(blank=True, null=True)),
                ('odds_captured_at', models.DateTimeField(blank=True, null=True)),
                ('prediction_generated_at', models.DateTimeField()),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pricing_integrity_status', models.CharField(choices=[('verified', 'Verified — price captured by the deterministic selector'), ('legacy_unverified', 'Legacy — original odds cannot be verified'), ('audit_excluded', 'Quarantined — known bad data'), ('missing_provenance', 'Missing or invalid price provenance')], db_index=True, default='legacy_unverified', max_length=24)),
                ('is_audit_excluded', models.BooleanField(db_index=True, default=False)),
                ('snapshot_hash', models.CharField(db_index=True, max_length=64)),
                ('snapshot_hash_version', models.CharField(default='v1', max_length=8)),
                ('correction_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('prediction', models.ForeignKey(blank=True, help_text='Latest-state row for this fixture. Convenience only — never the authoritative source for a published claim.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='core.predictionlog')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='core.predictionsnapshot')),
            ],
            options={
                'verbose_name': 'Prediction Snapshot',
                'ordering': ['-prediction_generated_at'],
            },
        ),
        migrations.AddField(
            model_name='publishedclaim',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_claims', to='core.predictionsnapshot'),
        ),
        migrations.AddIndex(
            model_name='predictionsnapshot',
            index=models.Index(fields=['fixture_id', '-prediction_generated_at'], name='core_predic_fixture_6337b3_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionsnapshot',
            index=models.Index(fields=['pricing_integrity_status'], name='core_predic_pricing_87806a_idx'),
        ),
        migrations.AddConstraint(
            model_name='predictionsnapshot',
            constraint=models.UniqueConstraint(fields=('prediction_run_id', 'fixture_id', 'market_type', 'predicted_outcome'), name='uniq_snapshot_per_run_fixture_market_outcome'),
        ),
    ]
