# Generated by Django 5.1.3 on 2026-08-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_predictionsnapshot_publishedclaim_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='scheduler', max_length=32, unique=True)),
                ('last_run_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('last_duration_seconds', models.FloatField(blank=True, null=True)),
                ('snapshots_created', models.IntegerField(default=0)),
                ('results_updated', models.IntegerField(default=0)),
                ('claims_settled', models.IntegerField(default=0)),
                ('last_failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('run_id', models.CharField(blank=True, default='', max_length=36)),
                ('interval_minutes', models.IntegerField(default=60)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduler Heartbeat',
                'verbose_name_plural': 'Scheduler Heartbeat',
            },
        ),
    ]
