# Generated by Django 5.1.3 on 2026-08-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_schedulerheartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('body_sha256', models.CharField(max_length=64)),
                ('prediction_run_id', models.CharField(db_index=True, max_length=64)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Ingest Request',
                'verbose_name_plural': 'Ingest Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
