# Generated by Django 5.1.3 on 2026-08-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_ingestrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalObservation',
            fields=[
                ('observation_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('ingestion_run_id', models.CharField(db_index=True, max_length=64)),
                ('source_payload_hash', models.CharField(max_length=64, unique=True)),
                ('fixture_id', models.IntegerField(db_index=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, default='', max_length=100)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField(db_index=True)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('hours_to_kickoff', models.FloatField(help_text='kickoff - observed_at, in hours. Negative means post-kickoff and the row must be excluded from decision evaluation.')),
                ('market', models.CharField(db_index=True, max_length=24)),
                ('outcome', models.CharField(max_length=24)),
                ('provider', models.CharField(default='sportmonks', max_length=32)),
                ('provider_type_id', models.IntegerField(blank=True, null=True)),
                ('provider_model_version', models.CharField(blank=True, default='', max_length=64)),
                ('provider_predicted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_probability', models.FloatField(help_text='Provider value for THIS outcome, exactly as supplied.')),
                ('normalized_probability', models.FloatField(help_text='raw/100 when the provider supplies percentages, else raw. No BetGlitch heuristic is applied here.')),
                ('raw_vector', models.JSONField()),
                ('vector_sum', models.FloatField(help_text='Sum of the normalized vector. Stored rather than assumed: a vector that does not sum to 1 must not be treated as a probability distribution.')),
                ('vector_complete', models.BooleanField(default=False, help_text='True only when every outcome the market requires is present.')),
                ('is_selected_outcome', models.BooleanField(default=False, help_text='Did the live pipeline pick this side?')),
                ('probability_gap', models.FloatField(blank=True, null=True)),
                ('form_multiplier', models.FloatField(blank=True, null=True)),
                ('form_inputs', models.JSONField(blank=True, help_text='Everything that produced form_multiplier, so the heuristic can be re-derived or reversed later.', null=True)),
                ('adjusted_score', models.FloatField(blank=True, help_text='min(normalized_probability * form_multiplier, cap). NOT a calibrated probability — see the class docstring.', null=True)),
                ('cap_applied', models.BooleanField(default=False)),
                ('market_score', models.FloatField(blank=True, help_text='Ranking score. Dimensionless.', null=True)),
                ('ranking_ev', models.FloatField(blank=True, null=True)),
                ('is_best_market', models.BooleanField(default=False)),
                ('selection_reason', models.CharField(blank=True, default='', max_length=120)),
                ('pipeline_version', models.CharField(blank=True, default='', max_length=80)),
                ('calculation_version', models.CharField(blank=True, default='', help_text='Frontend build/commit identifier for the code that produced these numbers.', max_length=80)),
                ('price_status', models.CharField(blank=True, default='', max_length=24)),
                ('odds', models.FloatField(blank=True, null=True)),
                ('bookmaker', models.CharField(blank=True, default='', max_length=64)),
                ('odds_captured_at', models.DateTimeField(blank=True, null=True)),
                ('odds_provenance', models.JSONField(blank=True, null=True)),
                ('provenance_complete', models.BooleanField(default=False)),
                ('market_price_vector', models.JSONField(blank=True, help_text='Every outcome price for this market, so a de-vigged baseline can be computed. A baseline from the selected outcome alone is not a baseline.', null=True)),
                ('price_vector_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signal Observation',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['fixture_id', 'market', 'outcome'], name='core_signal_fixture_77d8ea_idx'), models.Index(fields=['-observed_at'], name='core_signal_observe_4bf46e_idx'), models.Index(fields=['kickoff'], name='core_signal_kickoff_cf8221_idx'), models.Index(fields=['ingestion_run_id'], name='core_signal_ingesti_9be4e8_idx')],
            },
        ),
    ]
