# Generated by Django 5.1.3 on 2026-08-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_signalobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerheartbeat',
            name='stage_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulerheartbeat',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='running', max_length=16),
        ),
        migrations.CreateModel(
            name='FixtureResultObservation',
            fields=[
                ('result_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('fixture_id', models.IntegerField(db_index=True)),
                ('home_team', models.CharField(blank=True, default='', max_length=100)),
                ('away_team', models.CharField(blank=True, default='', max_length=100)),
                ('league', models.CharField(blank=True, default='', max_length=100)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField(db_index=True)),
                ('provider', models.CharField(default='sportmonks', max_length=32)),
                ('provider_status', models.CharField(db_index=True, help_text='Raw provider state string, stored verbatim.', max_length=32)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('score_type', models.CharField(blank=True, default='', help_text="Which score this is, e.g. 'CURRENT' / '2ND_HALF' / 'FT'.", max_length=24)),
                ('provider_result_at', models.DateTimeField(blank=True, null=True)),
                ('raw_scores', models.JSONField(blank=True, help_text='Every score entry the provider returned, so the chosen one can be re-derived rather than trusted.', null=True)),
                ('is_final', models.BooleanField(default=False, help_text='Provider status is an eligible final state AND both scores are present. Only these may be scored.')),
                ('is_scoreable', models.BooleanField(default=False, help_text='is_final AND the status permits deriving ordinary market outcomes. Extra-time and void-like states are never scoreable even when a score exists.')),
                ('ineligible_reason', models.CharField(blank=True, default='', max_length=64)),
                ('confirmed', models.BooleanField(default=False, help_text='A later independent observation returned the same final score. Unconfirmed finals are provisional.')),
                ('result_version', models.PositiveIntegerField(default=1)),
                ('is_correction', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('ingestion_run_id', models.CharField(db_index=True, max_length=64)),
                ('source_payload_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='core.fixtureresultobservation')),
            ],
            options={
                'verbose_name': 'Fixture Result Observation',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['fixture_id', '-result_version'], name='core_fixtur_fixture_f0fcef_idx'), models.Index(fields=['-captured_at'], name='core_fixtur_capture_022e91_idx'), models.Index(fields=['is_scoreable'], name='core_fixtur_is_scor_c9fdc3_idx')],
            },
        ),
    ]
