# Generated by Django 5.1.3 on 2026-08-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_schedulerheartbeat_stage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalobservation',
            name='variant_b_available',
            field=models.BooleanField(default=False, help_text='True only when the live heuristic actually produced an adjusted score for this row. Missing Variant B is reported, never inferred.'),
        ),
        migrations.AddField(
            model_name='signalobservation',
            name='variant_b_missing_reason',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
