# Generated by Django 5.1.3 on 2026-08-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_signalobservation_variant_b_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalobservation',
            name='live_activation_state',
            field=models.CharField(blank=True, default='', help_text="'shadow' when the form heuristic was computed but NOT applied to public output, 'live' when it was. Lets a row be read back as which regime produced it without rewriting old evidence.", max_length=16),
        ),
    ]
