# Generated by Django 5.1.3 on 2026-08-08 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_signalobservation_live_activation_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAnchor',
            fields=[
                ('anchor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('manifest', models.TextField()),
                ('manifest_version', models.CharField(max_length=64)),
                ('claim_count', models.IntegerField()),
                ('calendars', models.JSONField(default=list)),
                ('ots_proof', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Submitted to calendars, awaiting Bitcoin block'), ('CONFIRMED', 'Attested in a Bitcoin block')], db_index=True, default='PENDING', max_length=16)),
                ('bitcoin_block_height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAnchorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_hash', models.CharField(max_length=64)),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.claimanchor')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_entries', to='core.publishedclaim')),
            ],
            options={
                'indexes': [models.Index(fields=['claim'], name='core_claima_claim_i_5560c2_idx')],
                'unique_together': {('anchor', 'claim')},
            },
        ),
    ]
