# Generated by Django 5.1.3 on 2026-08-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_claimanchor_claimanchorentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankroll',
            name='staking_strategy',
            field=models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('fixed_percentage', 'Fixed Percentage')], default='fixed_amount', max_length=20),
        ),
    ]
