# Generated by Django 5.1.3 on 2026-08-17 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_fixturecontextobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyLabExperiment',
            fields=[
                ('experiment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_key', models.CharField(max_length=80)),
                ('version', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('market', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('shadow', 'Shadow'), ('candidate', 'Candidate'), ('validated', 'Validated'), ('retired', 'Retired')], db_index=True, default='shadow', max_length=16)),
                ('decision_horizon_hours', models.FloatField(default=1.0)),
                ('rules', models.JSONField(default=dict)),
                ('rules_hash', models.CharField(max_length=64, unique=True)),
                ('minimum_settled_for_review', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['strategy_key', 'version'],
                'constraints': [models.UniqueConstraint(fields=('strategy_key', 'version'), name='uniq_strategy_lab_key_version')],
            },
        ),
        migrations.CreateModel(
            name='StrategyLabObservation',
            fields=[
                ('observation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingestion_run_id', models.CharField(db_index=True, max_length=64)),
                ('source_payload_hash', models.CharField(max_length=64, unique=True)),
                ('fixture_id', models.IntegerField(db_index=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, default='', max_length=100)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField(db_index=True)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('hours_to_kickoff', models.FloatField()),
                ('market', models.CharField(max_length=40)),
                ('market_id', models.IntegerField(blank=True, null=True)),
                ('side', models.CharField(max_length=12)),
                ('handicap', models.FloatField()),
                ('label', models.CharField(max_length=120)),
                ('odds', models.FloatField()),
                ('bookmaker', models.CharField(max_length=64)),
                ('bookmaker_count', models.PositiveIntegerField(default=1)),
                ('price_min', models.FloatField()),
                ('price_max', models.FloatField()),
                ('odds_captured_at', models.DateTimeField()),
                ('price_provenance', models.JSONField(default=dict)),
                ('model_mass', models.FloatField()),
                ('expected_return_lower', models.FloatField()),
                ('expected_return_upper', models.FloatField()),
                ('robust_positive_edge', models.BooleanField(db_index=True, default=False)),
                ('calculation_version', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.strategylabexperiment')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLabSettlement',
            fields=[
                ('settlement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_version', models.PositiveIntegerField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('outcome', models.CharField(choices=[('full_win', 'Full win'), ('half_win', 'Half win'), ('push', 'Push'), ('half_loss', 'Half loss'), ('full_loss', 'Full loss')], max_length=16)),
                ('unit_profit', models.FloatField()),
                ('settlement_hash', models.CharField(max_length=64, unique=True)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='core.strategylabobservation')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_lab_settlements', to='core.fixtureresultobservation')),
            ],
            options={
                'ordering': ['-settled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='strategylabobservation',
            index=models.Index(fields=['experiment', 'fixture_id', 'side', 'handicap'], name='core_strate_experim_5a1040_idx'),
        ),
        migrations.AddIndex(
            model_name='strategylabobservation',
            index=models.Index(fields=['kickoff', 'robust_positive_edge'], name='core_strate_kickoff_3edb40_idx'),
        ),
        migrations.AddIndex(
            model_name='strategylabsettlement',
            index=models.Index(fields=['outcome'], name='core_strate_outcome_d61646_idx'),
        ),
        migrations.AddIndex(
            model_name='strategylabsettlement',
            index=models.Index(fields=['result_version'], name='core_strate_result__691f27_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategylabsettlement',
            constraint=models.UniqueConstraint(fields=('observation', 'result'), name='uniq_strategy_lab_observation_result'),
        ),
    ]
