# Generated by Django 5.1.3 on 2026-08-24

from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    """Create the telemetry table unless an earlier rollout already did so.

    Railway can briefly overlap replacement containers.  A previous rollout
    created this append-only table before its migration record was committed,
    so a normal ``CreateModel`` makes every later container fail at startup.
    Keeping the guard inside the migration preserves ordinary fresh-database
    behaviour while making recovery safe and repeatable.
    """

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        existing_tables = schema_editor.connection.introspection.table_names()
        if model._meta.db_table in existing_tables:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_gemfeedcache'),
    ]
    operations = [
        CreateModelIfMissing(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(db_index=True, max_length=64)),
                ('event_name', models.CharField(choices=[('page_viewed', 'Page Viewed'), ('page_dwell', 'Page Dwell'), ('home_primary_cta', 'Homepage Primary CTA'), ('home_verified_record_cta', 'Homepage Verified Record CTA'), ('explore_search', 'Explore Search'), ('fixture_opened', 'Fixture Opened'), ('research_shared', 'Research Shared'), ('published_proof_opened', 'Published Proof Opened'), ('registration_started', 'Registration Started'), ('registration_completed', 'Registration Completed'), ('first_login', 'First Login'), ('onboarding_action', 'Onboarding Action'), ('dashboard_visited', 'Dashboard Visited'), ('beta_page_viewed', 'Beta Page Viewed')], db_index=True, max_length=50)),
                ('surface', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('action', models.CharField(blank=True, default='', max_length=80)),
                ('has_results', models.BooleanField(blank=True, null=True)),
                ('duration_bucket', models.CharField(blank=True, choices=[('under_10s', 'Under 10 seconds'), ('10_to_30s', '10 to 30 seconds'), ('30_to_120s', '30 seconds to 2 minutes'), ('2_to_5m', '2 to 5 minutes'), ('over_5m', 'Over 5 minutes')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Product Event',
                'verbose_name_plural': 'Product Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', '-created_at'], name='core_produc_event_n_8a914d_idx'), models.Index(fields=['session_hash', 'created_at'], name='core_produc_session_e4d2fe_idx'), models.Index(fields=['surface', '-created_at'], name='core_produc_surface_f7c01b_idx')],
            },
        ),
    ]
