# Generated by Django 5.1.3 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_productevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSelection',
            fields=[
                ('selection_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('homepage', 'Homepage selection'), ('strategy', 'Strategy selection')], db_index=True, max_length=16)),
                ('source_key', models.CharField(db_index=True, max_length=80)),
                ('source_version', models.CharField(blank=True, default='', max_length=128)),
                ('source_ref', models.CharField(max_length=160, unique=True)),
                ('reason_code', models.CharField(choices=[('potential_value', 'Potential value'), ('strong_signal', 'Strong model signal'), ('strategy_match', 'Strategy match')], max_length=32)),
                ('fixture_id', models.IntegerField(db_index=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, default='', max_length=100)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField(db_index=True)),
                ('market_type', models.CharField(max_length=40)),
                ('predicted_outcome', models.CharField(max_length=120)),
                ('side', models.CharField(blank=True, default='', max_length=32)),
                ('line', models.FloatField(blank=True, null=True)),
                ('model_score', models.FloatField(blank=True, null=True)),
                ('odds', models.FloatField()),
                ('bookmaker', models.CharField(blank=True, default='', max_length=64)),
                ('bookmaker_count', models.PositiveIntegerField(default=1)),
                ('odds_captured_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('selection_hash', models.CharField(max_length=64, unique=True)),
                ('selection_hash_version', models.CharField(default='v1', max_length=8)),
                ('source_strategy_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_selections', to='core.strategylabobservation')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['category', '-published_at'], name='core_public_categor_ca9c77_idx'), models.Index(fields=['fixture_id', 'category'], name='core_public_fixture_69551a_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'source_key', 'fixture_id'), name='uniq_public_selection_source_fixture')],
            },
        ),
        migrations.CreateModel(
            name='PublicSelectionResult',
            fields=[
                ('selection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='result', serialize=False, to='core.publicselection')),
                ('status', models.CharField(choices=[('WON', 'Won'), ('HALF_WON', 'Half won'), ('PUSH', 'Push'), ('HALF_LOST', 'Half lost'), ('LOST', 'Lost'), ('VOID', 'Void'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('unit_profit', models.FloatField()),
                ('actual_score_home', models.IntegerField(blank=True, null=True)),
                ('actual_score_away', models.IntegerField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_source', models.CharField(default='sportmonks', max_length=64)),
                ('result_reference', models.CharField(blank=True, default='', max_length=160)),
            ],
            options={
                'verbose_name': 'Public Selection Result',
            },
        ),
    ]
