# Generated by Django 5.1.3 on 2026-09-05 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_publicselectionclosingprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=64)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=dict)),
                ('evidence_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-generated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSelectionAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('fixture_id', models.IntegerField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.publicselection')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.selectionboard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('version', 'fixture_id'), name='uniq_homepage_version_fixture')],
            },
        ),
    ]
