version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
      - REDIS_URL=redis://redis:6379/0
      - SPORTMONKS_API_TOKEN=${SPORTMONKS_API_TOKEN}
      - ODDSAPI_KEY=${ODDSAPI_KEY}
    networks:
      - smartbet-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - smartbet-network

networks:
  smartbet-network:

volumes:
  redis-data: 